server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: Q2CzQbWvmN09JDFiCyEdNLYZ8_5biwJGFhvH4E_6
  secretKey: YhC0YlQKQW7_4yC3Lxn6BzOgLeWuieMK8sar188Y
  bucket: my-blog-space0
  domain: http://sx2a6l4a3.hn-bkt.clouddn.com/